#!/usr/bin/env bash

set -e
set -o pipefail

cd "$(dirname "$0")/.."

skip_migrations=false

help() {
  echo "Usage: $0 [-s] [-h]"
  echo
  echo "Updates the local environment, using cache if present."
  echo
  echo "Options:"
  echo "  -s Skip migrations"
  echo "  -h Show this message and exit"
  echo
}

while getopts 'sh' flag; do
  case "${flag}" in
    s) skip_migrations=true ;;
    h) help; exit 0 ;;
    *) help >&2; exit 1;;
  esac
done

docker compose build

if [ "$skip_migrations" = false ]; then
  script/migrate -n
fi
